import turtle
import random
import time
import winsound

f = open('gameData.txt', 'a')


def nobody(topper):
    def fun2(k,add):
        wn.delay(1)
        tur.color('black')
        mera = 5 - a
        tur.up()
        tur.goto(-500,-100)
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.bk(90)
        tur.write(f'Player 1 : {topper}',font=('Times New Roman', 15, 'bold'))
        tur.goto(-600,100-3*k)
        tur.write(f'\nI Have Chosen {a} Chalks Out Of {add+5}\n',font=('Times New Roman', 11, 'bold'))
        tur.left(60)
        tur.up()
        tur.goto(380,100-3*k)
        tur.down()
        tur.write(f'\nI Have Chosen {mera} Chalks Out Of {add+5-a}\n',font=('Times New Roman', 11, 'bold'))
        tur.up()
        tur.goto(600,-100)
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.goto(500.00,-47.06)
        tur.write('Player 2 : ME',font=('Times New Roman', 15, 'bold'))
        tur.left(60)
        for i in range(k,k+5):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
            
        sticks(k,add)

    def sticks(k,add):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            add -= 5
            wn.onkey(fun2(k,add),'d')
            wn.listen()
        else:
            f = open('gameData.txt', 'a')
            f.write(str(topper))
            f.write(" :2 ")
            f.close()
            wn.delay(0.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(600,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(600,-100)
            tur.up()
            tur.color('#ff9933')
            tur.goto(600,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(600,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {topper}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.write(f'\nCongratulations To Myself!! I Won The Challenge :)',font=('Times New Roman',15,'italic'))
            tur.up()
            tur.goto(-200,100)
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('#ff9933')
            tur.goto(-500,90)
            tur.color("brown")
            tur.write(f"{topper}, You Are Real Match Winner",font=('Times New Roman',49,'italic','bold'))
            
    tur = turtle.Turtle()
    wn = turtle.Screen()
    tur.color("black")
    wn.delay(10)
    wn.clear()
    wn.clear()
    wn.bgcolor('#ff9933')
    tur.width(10)
    tur.speed(0)
    tur.hideturtle()
    tur.up()
    tur.goto(300,105)
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.down()
    tur.left(60)
    tur.fd(100)
    tur.right(60)
    tur.bk(550)
    tur.goto(-300,105)
    tur.up()
    tur.goto(300,105)
    tur.left(60)
    tur.fd(100)
    tur.left(30)
    tur.down()
    tur.bk(315)
    tur.goto(300,-210)
    tur.end_fill()
    tur.right(30)
    tur.width(2)
    tur.fd(110)
    tur.color('#3d3d29')
    tur.begin_fill()
    tur.fillcolor('#3d3d29')
    tur.fd(200)
    tur.right(60)
    tur.bk(99)
    tur.end_fill()
    tur.width(10)
    tur.color('white')
    for i in range(1,22):
        if i%2==0:
            tur.up()
            tur.goto(i*10,210)
            tur.down()
            tur.goto(i*10,-210)
        else:
            tur.up()
            tur.goto(-i*10,210)
            tur.down()
            tur.goto(-i*10,-210)

    tur.up()
    tur.color('black')
    tur.goto(300,105)
    tur.down()
    tur.goto(-300,105)
    tur.down()
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.goto(-300,-210)
    tur.goto(300,-210)
    tur.goto(300,105)
    tur.end_fill()
    tur.up()
    tur.color('white')
    tur.goto(-200,0)
    tur.write('''As You Know There Are 21 Chalks
Now, You have to select chalks according to rules''',move=True, align='left', font=('Times New Roman', 18, 'bold', 'italic'))
    k = 1
    addition = 21
    sticks(k,addition)

def last_game(topper):
    wn = turtle.Screen()
    wn.delay(10)
    nobody(topper)


def stick_picker3(match, names):
    def fun1(k, add, match, names):
        wn.delay(1)
        add-=a
        tur.up()
        tur.goto(380,100-3*k)
        tur.down()
        tur.write(f'\n {match} Have Chosen {a} Chalks Out Of {add + a}\n',font=('Times New Roman', 11, 'bold'))
        tur.up()
        tur.goto(600,-100)
        tur.color("black")
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.goto(500.00,-47.06)
        #tur.write(f'Player 2 : match1[1]',font=('Times New Roman', 15, 'bold'))
        tur.left(60)
        for i in range(k,k+a):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
        sticksByOne(k, add, match, names, l)

    def sticksByTwo(k, add, match, names):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            fun1(k, add, match, names)
        else:
            wn.delay(0.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(-500,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(-500,-100)
            tur.up()
            tur.goto(-500,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {match}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.color('yellow')
            tur.write(f'\nCongratulations {names}!! You Won The Challenge :)',font=('Times New Roman',15,'italic'))
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('black')
            tur.speed(0)
            tur.hideturtle()
            tur.width(10)
            tur.color('brown')
            tur.up()
            tur.begin_fill()
            tur.goto(-300,200)
            tur.fillcolor('#006622')
            tur.down()
            tur.goto(300,200)
            tur.goto(300,-200)
            tur.goto(-300,-200)
            tur.goto(-300,200)
            tur.end_fill()
            tur.up()
            tur.goto(-290,100)
            tur.color('white')
            tur.write("The Intelligent Chalk Picker :-\n The Final Game.... \n ALERT => \n This Game Is With Computer....",font=('Times New Roman', 17, 'bold'))
            time.sleep(5)
            f = open('gameData.txt', 'a')
            f.write(str(match))
            f.write(" :1 \n")
            f.close()
            last_game(names)

            
    def fun2(k, add, match1, names, l):    
        wn.delay(1)
        tur.color('black')
        tur.up()
        tur.goto(-500,-100)
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.bk(90)
        tur.goto(-600,100-3*k)
        tur.write(f'\n{names} Have Chosen {a} Chalks Out Of {add+a}\n',font=('Times New Roman', 11, 'bold'))
        tur.left(60)
        for i in range(k,k+a):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
        
        sticksByTwo(k, add, match1, names)

    def sticksByOne(k, add, match1, names, l):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            add -= a
            wn.onkey(fun2(k, add, match, names, l),'d')
            wn.listen()
        else:
            wn.delay(.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(600,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(600,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {names}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.color('yellow')
            tur.write(f'\nCongratulations {match}!! You Won The Challenge :)',font=('Times New Roman',15,'italic'))
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('black')
            tur.speed(0)
            tur.hideturtle()
            tur.width(10)
            tur.color('brown')
            tur.up()
            tur.begin_fill()
            tur.goto(-300,200)
            tur.fillcolor('#006622')
            tur.down()
            tur.goto(300,200)
            tur.goto(300,-200)
            tur.goto(-300,-200)
            tur.goto(-300,200)
            tur.end_fill()
            tur.up()
            tur.goto(-290,130)
            tur.color('white')
            tur.write("The Intelligent Chalk Picker :-\n The Final Game.... \n ALERT => \n This Game Is With Computer....",font=('Times New Roman', 17, 'bold'))
            f = open('gameData.txt', 'a')
            f.write(str(names))
            f.write(" :1 \n")
            f.close()
            time.sleep(5)
            last_game(match)
            
            
    tur = turtle.Turtle()
    wn = turtle.Screen()
    wn.delay(10)
    wn.clear()
    wn.bgcolor('#ff9933')
    tur.width(10)
    tur.speed(0)
    tur.hideturtle()
    tur.up()
    tur.goto(300,105)
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.down()
    tur.left(60)
    tur.fd(100)
    tur.right(60)
    tur.bk(550)
    tur.goto(-300,105)
    tur.up()
    tur.goto(300,105)
    tur.left(60)
    tur.fd(100)
    tur.left(30)
    tur.down()
    tur.bk(315)
    tur.goto(300,-210)
    tur.end_fill()
    tur.right(30)
    tur.width(2)
    tur.fd(110)
    tur.color('#3d3d29')
    tur.begin_fill()
    tur.fillcolor('#3d3d29')
    tur.fd(200)
    tur.right(60)
    tur.bk(99)
    tur.end_fill()
    tur.width(10)
    tur.color('white')
    for i in range(1,22):
        if i%2==0:
            tur.up()
            tur.goto(i*10,210)
            tur.down()
            tur.goto(i*10,-210)
        else:
            tur.up()
            tur.goto(-i*10,210)
            tur.down()
            tur.goto(-i*10,-210)

    tur.up()
    tur.color('black')
    tur.goto(300,105)
    tur.down()
    tur.goto(-300,105)
    tur.down()
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.goto(-300,-210)
    tur.goto(300,-210)
    tur.goto(300,105)
    tur.end_fill()
    tur.up()
    tur.color('white')
    tur.goto(-200,0)
    tur.write('''As You Know There Are 21 Chalks
Now, You have to select chalks according to rules''',move=True, align='left', font=('Times New Roman', 18, 'bold', 'italic'))
    k = 1
    l = 1
    addition = 21
    wn.delay(1)
    tur.up()
    tur.color('black')
    tur.goto(-500,-100)
    tur.down()
    tur.circle(25)
    tur.right(90)
    tur.fd(50)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.right(30)
    tur.bk(25)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.up()
    tur.goto(500.00,-47.06)
    tur.write(f'Player 2 : {match}',font=('Times New Roman', 15, 'bold'))
    tur.up()
    tur.left(60)
    wn.delay(1)
    tur.up()
    tur.down()
    tur.up()
    tur.goto(600,-100)
    tur.color("black")
    tur.down()
    tur.circle(25)
    tur.right(90)
    tur.fd(50)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.right(30)
    tur.bk(25)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.up()
    tur.goto(-550, -47.06)
    tur.write(f'Player 1 : {names}',font=('Times New Roman', 15, 'bold'))
    tur.up()
    tur.left(60)
    sticksByOne(k, addition, match, names, l)

def third_game(match, names):
    wn = turtle.Screen()
    wn.delay(10)
    stick_picker3(match, names)

def stick_picker2(match, names):
    def fun1(k, add, match, names):
        wn.delay(1)
        add-=a
        tur.up()
        tur.goto(380,100-3*k)
        tur.down()
        tur.write(f'\n {names[1]} Have Chosen {a} Chalks Out Of {add + a}\n',font=('Times New Roman', 11, 'bold'))
        tur.up()
        tur.goto(600,-100)
        tur.color("black")
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.goto(500.00,-47.06)
        #tur.write(f'Player 2 : match1[1]',font=('Times New Roman', 15, 'bold'))
        tur.left(60)
        for i in range(k,k+a):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
        sticksByOne(k, add, match, names, l)

    def sticksByTwo(k, add, match, names):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            fun1(k, add, match, names)
        else:
            wn.delay(0.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(-500,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(-500,-100)
            tur.up()
            tur.goto(-500,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {names[1]}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.color('yellow')
            tur.write(f'\nCongratulations {names[0]}!! You Won The Challenge :)',font=('Times New Roman',15,'italic'))
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('black')
            tur.speed(0)
            tur.hideturtle()
            tur.width(10)
            tur.color('brown')
            tur.up()
            tur.begin_fill()
            tur.goto(-300,200)
            tur.fillcolor('#006622')
            tur.down()
            tur.goto(300,200)
            tur.goto(300,-200)
            tur.goto(-300,-200)
            tur.goto(-300,200)
            tur.end_fill()
            tur.up()
            tur.goto(-290,130)
            tur.color('white')
            tur.write("The Intelligent Chalk Picker :-\n The Next Game....",font=('Times New Roman', 17, 'bold'))
            time.sleep(5)
            f = open('gameData.txt', 'a')
            f.write(str(names[1]))
            f.write(" :0 \n")
            f.close()
            third_game(match, names[0])

            
    def fun2(k, add, match1, names, l):    
        wn.delay(1)
        tur.color('black')
        tur.up()
        tur.goto(-500,-100)
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.bk(90)
        tur.goto(-600,100-3*k)
        tur.write(f'\n{names[0]} Have Chosen {a} Chalks Out Of {add+a}\n',font=('Times New Roman', 11, 'bold'))
        tur.left(60)
        for i in range(k,k+a):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
        
        sticksByTwo(k, add, match1, names)

    def sticksByOne(k, add, match1, names, l):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            add -= a
            wn.onkey(fun2(k, add, match, names, l),'d')
            wn.listen()
        else:
            wn.delay(.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(600,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(600,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {names[0]}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.color('yellow')
            tur.write(f'\nCongratulations {names[1]}!! You Won The Challenge :)',font=('Times New Roman',15,'italic'))
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('black')
            tur.speed(0)
            tur.hideturtle()
            tur.width(10)
            tur.color('brown')
            tur.up()
            tur.begin_fill()
            tur.goto(-300,200)
            tur.fillcolor('#006622')
            tur.down()
            tur.goto(300,200)
            tur.goto(300,-200)
            tur.goto(-300,-200)
            tur.goto(-300,200)
            tur.end_fill()
            tur.up()
            tur.goto(-290,130)
            tur.color('white')
            tur.write("The Intelligent Chalk Picker :-\n The Next Game....",font=('Times New Roman', 17, 'bold'))
            time.sleep(5)
            f = open('gameData.txt', 'a')
            f.write(str(names[0]))
            f.write(" :0 \n")
            f.close()
            third_game(match, names[1])
            
            
    tur = turtle.Turtle()
    wn = turtle.Screen()
    wn.delay(10)
    wn.clear()
    wn.bgcolor('#ff9933')
    tur.width(10)
    tur.speed(0)
    tur.hideturtle()
    tur.up()
    tur.goto(300,105)
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.down()
    tur.left(60)
    tur.fd(100)
    tur.right(60)
    tur.bk(550)
    tur.goto(-300,105)
    tur.up()
    tur.goto(300,105)
    tur.left(60)
    tur.fd(100)
    tur.left(30)
    tur.down()
    tur.bk(315)
    tur.goto(300,-210)
    tur.end_fill()
    tur.right(30)
    tur.width(2)
    tur.fd(110)
    tur.color('#3d3d29')
    tur.begin_fill()
    tur.fillcolor('#3d3d29')
    tur.fd(200)
    tur.right(60)
    tur.bk(99)
    tur.end_fill()
    tur.width(10)
    tur.color('white')
    for i in range(1,22):
        if i%2==0:
            tur.up()
            tur.goto(i*10,210)
            tur.down()
            tur.goto(i*10,-210)
        else:
            tur.up()
            tur.goto(-i*10,210)
            tur.down()
            tur.goto(-i*10,-210)

    tur.up()
    tur.color('black')
    tur.goto(300,105)
    tur.down()
    tur.goto(-300,105)
    tur.down()
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.goto(-300,-210)
    tur.goto(300,-210)
    tur.goto(300,105)
    tur.end_fill()
    tur.up()
    tur.color('white')
    tur.goto(-200,0)
    tur.write('''As You Know There Are 21 Chalks
Now, You have to select chalks according to rules''',move=True, align='left', font=('Times New Roman', 18, 'bold', 'italic'))
    k = 1
    l = 1
    addition = 21
    wn.delay(1)
    tur.up()
    tur.color('black')
    tur.goto(-500,-100)
    tur.down()
    tur.circle(25)
    tur.right(90)
    tur.fd(50)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.right(30)
    tur.bk(25)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.up()
    tur.goto(500.00,-47.06)
    tur.write(f'Player 2 : {names[1]}',font=('Times New Roman', 15, 'bold'))
    tur.up()
    tur.left(60)
    wn.delay(1)
    tur.up()
    tur.down()
    tur.up()
    tur.goto(600,-100)
    tur.color("black")
    tur.down()
    tur.circle(25)
    tur.right(90)
    tur.fd(50)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.right(30)
    tur.bk(25)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.up()
    tur.goto(-550, -47.06)
    tur.write(f'Player 1 : {names[0]}',font=('Times New Roman', 15, 'bold'))
    tur.up()
    tur.left(60)
    sticksByOne(k, addition, match, names, l)

def second_game(match, names):
    wn = turtle.Screen()
    wn.delay(10)
    stick_picker2(match, names)

def stick_picker(match1, names):
    def fun1(k, add, match1, names):
        wn.delay(1)
        add-=a
        tur.up()
        tur.goto(380,100-3*k)
        tur.down()
        tur.write(f'\n {match1[1]} Have Chosen {a} Chalks Out Of {add + a}\n',font=('Times New Roman', 11, 'bold'))
        tur.up()
        tur.goto(600,-100)
        tur.color("black")
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.goto(500.00,-47.06)
        #tur.write(f'Player 2 : match1[1]',font=('Times New Roman', 15, 'bold'))
        tur.left(60)
        for i in range(k,k+a):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
        sticksByOne(k, add, match1, names, l)

    def sticksByTwo(k, add, match1, names):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            fun1(k, add, match1, names)
        else:
            wn.delay(0.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(-500,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(-500,-100)
            tur.up()
            tur.goto(-500,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {match1[1]}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.color('yellow')
            tur.write(f'\nCongratulations {match1[0]}!! You Won The Challenge :)',font=('Times New Roman',15,'italic'))
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('black')
            tur.speed(0)
            tur.hideturtle()
            tur.width(10)
            tur.color('brown')
            tur.up()
            tur.begin_fill()
            tur.goto(-300,200)
            tur.fillcolor('#006622')
            tur.down()
            tur.goto(300,200)
            tur.goto(300,-200)
            tur.goto(-300,-200)
            tur.goto(-300,200)
            tur.end_fill()
            tur.up()
            tur.goto(-290,130)
            tur.color('white')
            tur.write("The Intelligent Chalk Picker :-\n The Next Game....",font=('Times New Roman', 17, 'bold'))
            time.sleep(5)
            f = open('gameData.txt', 'a')
            f.write('\n'+str(match1[1]))
            f.write(" :0 \n")
            f.close()
            turtle.ontimer(second_game(match1[0], names),10000)

            
    def fun2(k, add, match1, names, l):    
        wn.delay(1)
        tur.color('black')
        tur.up()
        tur.goto(-500,-100)
        tur.down()
        tur.circle(25)
        tur.right(90)
        tur.fd(50)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.right(30)
        tur.bk(25)
        tur.right(30)
        tur.fd(25)
        tur.bk(25)
        tur.left(60)
        tur.fd(25)
        tur.bk(25)
        tur.up()
        tur.bk(90)
        tur.goto(-600,100-3*k)
        tur.write(f'\n{match1[0]} Have Chosen {a} Chalks Out Of {add+a}\n',font=('Times New Roman', 11, 'bold'))
        tur.left(60)
        for i in range(k,k+a):
            if i%2==0:
                tur.up()
                tur.goto(i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                k+=1
            else:
                tur.up()
                tur.goto(-i*10,210)
                tur.down()
                winsound.PlaySound('Woosh.wav', winsound.SND_ASYNC)
                tur.left(90)
                tur.bk(100)
                tur.right(90)
                tur.up()
                wn.delay(150)
                k+=1
        
        sticksByTwo(k, add, match1, names)

    def sticksByOne(k, add, match1, names, l):
        global a
        if add > 1:
            a = int(wn.numinput('THE GAME','CHOOSE NUMBER OF CHALKS'))
            while a>4:
                a = int(wn.numinput('!! WARNING !!','CHOOSE NUMBER OF CHALKS ACCORDING TO RULE'))
            add -= a
            wn.onkey(fun2(k, add, match1, names, l),'d')
            wn.listen()
        else:
            wn.delay(.1)
            tur.up()
            tur.color('#ff9933')
            tur.goto(600,-100)
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.left(60)
            tur.goto(600,-100)
            tur.color('yellow')
            tur.down()
            tur.circle(25)
            tur.right(90)
            tur.fd(50)
            tur.right(30)
            tur.fd(25)
            tur.bk(25)
            tur.left(60)
            tur.fd(25)
            tur.bk(25)
            tur.right(30)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.right(120)
            tur.fd(25)
            tur.bk(25)
            tur.up()
            tur.bk(90)
            tur.goto(-150,-50)
            tur.color('yellow')
            tur.write(f'Sorry {match1[0]}!! You Lost The Challenge :(\n',font=('Times New Roman',15,'italic'))
            tur.color('yellow')
            tur.write(f'\nCongratulations {match1[1]}!! You Won The Challenge :)',font=('Times New Roman',15,'italic'))
            time.sleep(5)
            wn.clear()
            wn.bgcolor('white')
            wn.bgcolor('black')
            tur.speed(0)
            tur.hideturtle()
            tur.width(10)
            tur.color('brown')
            tur.up()
            tur.begin_fill()
            tur.goto(-300,200)
            tur.fillcolor('#006622')
            tur.down()
            tur.goto(300,200)
            tur.goto(300,-200)
            tur.goto(-300,-200)
            tur.goto(-300,200)
            tur.end_fill()
            tur.up()
            tur.goto(-290,130)
            tur.color('white')
            tur.write("The Intelligent Chalk Picker :-\n The Next Game....",font=('Times New Roman', 17, 'bold'))
            time.sleep(5)
            f = open('gameData.txt', 'a')
            f.write('\n'+str(match1[0]))
            f.write(" :0 \n")
            f.close()
            turtle.ontimer(second_game(match1[1], names),10000)

    tur = turtle.Turtle()
    wn = turtle.Screen()
    wn.bgcolor('#ff9933')
    tur.width(10)
    tur.speed(0)
    tur.hideturtle()
    tur.up()
    tur.goto(300,105)
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.down()
    tur.left(60)
    tur.fd(100)
    tur.right(60)
    tur.bk(550)
    tur.goto(-300,105)
    tur.up()
    tur.goto(300,105)
    tur.left(60)
    tur.fd(100)
    tur.left(30)
    tur.down()
    tur.bk(315)
    tur.goto(300,-210)
    tur.end_fill()
    tur.right(30)
    tur.width(2)
    tur.fd(110)
    tur.color('#3d3d29')
    tur.begin_fill()
    tur.fillcolor('#3d3d29')
    tur.fd(200)
    tur.right(60)
    tur.bk(99)
    tur.end_fill()
    tur.width(10)
    tur.color('white')
    for i in range(1,22):
        if i%2==0:
            tur.up()
            tur.goto(i*10,210)
            tur.down()
            tur.goto(i*10,-210)
        else:
            tur.up()
            tur.goto(-i*10,210)
            tur.down()
            tur.goto(-i*10,-210)

    tur.up()
    tur.color('black')
    tur.goto(300,105)
    tur.down()
    tur.goto(-300,105)
    tur.down()
    tur.begin_fill()
    tur.fillcolor('brown')
    tur.goto(-300,-210)
    tur.goto(300,-210)
    tur.goto(300,105)
    tur.end_fill()
    tur.up()
    tur.color('white')
    tur.goto(-200,0)
    tur.write('''As You Know There Are 21 Chalks
Now, You have to select chalks according to rules''',move=True, align='left', font=('Times New Roman', 18, 'bold', 'italic'))
    k = 1
    l = 1
    addition = 21
    wn.delay(1)
    tur.up()
    tur.color('black')
    tur.goto(-500,-100)
    tur.down()
    tur.circle(25)
    tur.right(90)
    tur.fd(50)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.right(30)
    tur.bk(25)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.up()
    tur.goto(500.00,-47.06)
    tur.write(f'Player 2 : {match1[1]}',font=('Times New Roman', 15, 'bold'))
    tur.up()
    tur.left(60)
    wn.delay(1)
    tur.up()
    tur.down()
    tur.up()
    tur.goto(600,-100)
    tur.color("black")
    tur.down()
    tur.circle(25)
    tur.right(90)
    tur.fd(50)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.right(30)
    tur.bk(25)
    tur.right(30)
    tur.fd(25)
    tur.bk(25)
    tur.left(60)
    tur.fd(25)
    tur.bk(25)
    tur.up()
    tur.goto(-550, -47.06)
    tur.write(f'Player 1 : {match1[0]}',font=('Times New Roman', 15, 'bold'))
    tur.up()
    tur.left(60)
    sticksByOne(k, addition, match1, names, l)

def clear(match1, names):
    wn.clear()
    stick_picker(match1, names)
    
def two_players(names):
    match1 = random.choices(names,k=2)
    while match1[0] == match1[1]:
        match1 = random.choices(names,k=2)
    names = list(set(names)-set(match1))
    tur.color('red')
    wn.bgcolor('#ffd9b3')
    tur.write(f"\tMATCH 1\n \n\t {match1[0]} Vs {match1[1]}",move=True, align='left', font=('Times New Roman', 40, 'bold', 'italic','underline'))
    tur.up()
    tur.color('blue')
    tur.goto(-300,-100)
    tur.write(f"\tMATCH 2\n \n\t {names[0]} Vs {names[1]}",move=True, align='left', font=('Times New Roman', 40, 'bold', 'italic','underline'))
    time.sleep(5)
    turtle.listen()
    wn.onkey(clear(match1, names), 's')

def just_to_start():
    names = []
    name = ''
    players = 0
    while players!=4:
        players += 1
        name = (wn.textinput('PROMPT',f'WRITE YOUR NAME HERE PLAYER {players}')).title()
        names.append(name)
        
    wn.clear()
    two_players(names)
    
def rules():
    tur.down()
    wn.clear()
    wn.bgcolor('#3d3d29')
    tur.up()
    tur.goto(-250,0)
    tur.write('''
RULES:-
1) There Are 21 Chalks In The Chalk Box.
2) This Game Requires 4 Players To Play.
3) Both Players Can Pick 1/2/3 or 4 Chalks.
4) No One Can Pick Chalks Greater Than 4.
5) The Player Who Have To Pick Last Chalk Will Have To Pay For The Box
SO,
Are You Clear With Rules ?
If Yes Click 'y'
Else Click 'n'. ''',font=('Times New Roman', 15, 'bold'))
    tur.goto(-300,100)
    tur.down()
    wn.onkey(just_to_start, 'y')
    wn.onkey(rules, 'n')

import datetime
with open('gameDateData.txt','a') as file:
    file.write('%s \n'%(datetime.datetime.now()))

tur = turtle.Turtle()
wn = turtle.Screen()
tur.hideturtle()
wn.bgcolor('black')
tur.speed(0)
tur.hideturtle()
tur.width(10)
tur.color('brown')
tur.up()
tur.begin_fill()
tur.goto(-300,200)
tur.fillcolor('#006622')
tur.down()
tur.goto(300,200)
tur.goto(300,-200)
tur.goto(-300,-200)
tur.goto(-300,200)
tur.end_fill()
tur.up()
tur.goto(-290,130)
tur.color('white')
tur.write("The Intelligent Chalk Picker :-\n Rules Of The Game Will Be Displayed After..... \n",font=('Times New Roman', 15, 'bold'))
time.sleep(5)
rules()
turtle.listen()


# All the functions contain interactive windows which are made using co-ordinates so it 
# could be possible that in smaller laptops some part of that gaming window will not appear
# so it could be because of above issue.